stages:
    - build
    - check
    - test
    - package

build-job:
    stage: build
    script:
        - echo "Compiling the code..."
        - cd code
        - ./gradlew assemble 2>&1 | tee output_1.txt
        - echo "Compile complete."
    artifacts:
        when: always
        paths:
            - code/output_1.txt

spotbugs-job:
    when: always
    stage: check
    script:
        - echo "Running SpotBugs tests..."
        - cd code
        - ./gradlew spotbugsMain 2>&1 | tee output_2.txt
        - ./gradlew spotbugsTest 2>&1 | tee output_3.txt
        - echo "SpotBugs tests complete."
    artifacts:
        when: always
        paths:
            - code/output_2.txt
            - code/output_3.txt

checkstyle-job:
    when: always
    stage: check
    script:
        - echo "Checkstyle..."
        - cd code
        - ./gradlew check 2>&1 | tee output_4.txt
        - echo "Checkstyle complete."
    artifacts:
        when: always
        paths:
            - code/output_4.txt

spotless-job:
    when: always
    stage: check
    script:
        - echo "Spotless..."
        - cd code
        - ./gradlew spotlessJavaCheck 2>&1 | tee output_5.txt
        - echo "Spotless complete."
    artifacts:
        when: always
        paths:
            - code/output_5.txt

junit-job:
    when: always
    stage: test
    script:
        - echo "Running JUnit tests..."
        - cd code
        - ./gradlew test 2>&1 | tee output_6.txt
        - echo "JUnit tests complete."
    artifacts:
        when: always
        paths:
            - code/output_6.txt

package-job:
    when: always
    stage: package
    script:
        - cd code
        - cat output_*.txt 2>&1 | tee output_7.txt
    artifacts:
        paths:
            - code/output_7.txt
