stages:
    - build
    - test
    - package

build-job:
    stage: build
    script:
        - echo "Compiling the code..."
        - cd code
        - ./gradlew assemble > assemble.txt
        - echo "Compile complete."

junit-job:
    stage: test
    script:
        - echo "Running JUnit tests..."
        - cd code
        - ./gradlew test > junit.txt
        - echo "JUnit tests complete."

spotbugs-job:
    stage: test
    script:
        - echo "Running SpotBugs tests..."
        - cd code
        - ./gradlew spotbugsMain > spotbugsMain.txt
        - ./gradlew spotbugsTest > spotbugsTest.txt
        - echo "SpotBugs tests complete."

checkstyle-job:
    stage: test
    script:
        - echo "Checkstyle..."
        - cd code
        - ./gradlew check > checkstyle.txt
        - echo "Checkstyle complete."

spotless-job:
    stage: test
    script:
        - echo "Spotless..."
        - cd code
        - ./gradlew spotlessJavaCheck > spotless.txt
        - echo "Spotless complete."

package-job:
    stage: package
    script:
        - cd code
        - cat assemble.txt junit.txt spotbugsMain.txt spotbugsTest.txt checkstyle.txt spotless.txt | gzip > tests.gz
    artifacts:
        paths:
            - tests.gz
