stages:
    - build
    - test
    - package

build-job:
    stage: build
    script:
        - echo "Compiling the code..."
        - cd code
        - ./gradlew assemble > assemble.txt 2>&1
        - echo "Compile complete."
    artifacts:
        paths:
            - code/assemble.txt

junit-job:
    stage: test
    script:
        - echo "Running JUnit tests..."
        - cd code
        - ./gradlew test > junit.txt 2>&1
        - echo "JUnit tests complete."
    artifacts:
        paths:
            - code/junit.txt

spotbugs-job:
    stage: test
    script:
        - echo "Running SpotBugs tests..."
        - cd code
        - ./gradlew spotbugsMain > spotbugsMain.txt 2>&1
        - ./gradlew spotbugsTest > spotbugsTest.txt 2>&1
        - echo "SpotBugs tests complete."
    artifacts:
        paths:
            - code/spotbugsMain.txt
            - code/spotbugsTest.txt

checkstyle-job:
    stage: test
    script:
        - echo "Checkstyle..."
        - cd code
        - ./gradlew check > checkstyle.txt 2>&1
        - echo "Checkstyle complete."
    artifacts:
        paths:
            - code/checkstyle.txt

spotless-job:
    stage: test
    script:
        - echo "Spotless..."
        - cd code
        - ./gradlew spotlessJavaCheck > spotless.txt 2>&1
        - echo "Spotless complete."
    artifacts:
        paths:
            - code/spotless.txt

package-job:
    when: always
    stage: package
    script:
        - cd code
        - cat assemble.txt junit.txt spotbugsMain.txt spotbugsTest.txt checkstyle.txt spotless.txt > tests.txt
        - gzip -k tests.txt
    artifacts:
        paths:
            - code/tests.txt
            - code/tests.txt.gz
