name: Java CI

on: [ pull_request ]

jobs:

    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Set up JDK 17
                uses: actions/setup-java@v2
                with:
                    java-version: '17'
                    distribution: 'adopt'
            -   name: Validate Gradle wrapper
                uses: gradle/wrapper-validation-action@v1
            -   name: Build with Gradle
                run: ./gradlew assemble
                working-directory: code

    junit-test:
        needs: build
        name: JUnit Test
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Set up JDK 17
                uses: actions/setup-java@v2
                with:
                    java-version: '17'
                    distribution: 'adopt'
            -   name: Test with JUnit
                run: |
                    ./gradlew test
                working-directory: code
            -   name: JUnit Test Report
                uses: mikepenz/action-junit-report@v2
                if: always() # always run even if the previous step fails
                with:
                    report_paths: '**/build/test-results/test/TEST-*.xml'

    spotbugs-test:
        needs: build
        name: SpotBugs Test
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Set up JDK 17
                uses: actions/setup-java@v2
                with:
                    java-version: '17'
                    distribution: 'adopt'
            -   name: Test with SpotBugs
                run: |
                    ./gradlew spotbugsMain
                    ./gradlew spotbugsTest
                working-directory: code
            -   name: SpotBugs Test Report
                uses: jwgmeligmeyling/spotbugs-github-action@master
                with:
                    path: '**/spotbugsXml.xml'
                    name: 'SpotBugs Test Report'

    checkstyle-test:
        needs: build
        name: Checkstyle Test
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Set up JDK 17
                uses: actions/setup-java@v2
                with:
                    java-version: '17'
                    distribution: 'adopt'
            -   name: Test with Checkstyle
                run: ./gradlew check
                working-directory: code
            -   uses: jwgmeligmeyling/checkstyle-github-action@master
                with:
                    path: '**/checkstyle/*.xml'

    spotless-java-format-test:
        needs: build
        name: Spotless Test
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Set up JDK 17
                uses: actions/setup-java@v2
                with:
                    java-version: '17'
                    distribution: 'adopt'
            -   name: Test with Spotless
                run: ./gradlew spotlessJavaCheck
                working-directory: code
